# -*- coding: utf-8 -*-
"""perceptron.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/184SJkYJu3Une2zgTSvDSNdx8Arn0o9YX

# Atividade de Redes Neurais de Emanuel Lopes Silva

Este notebook foi desenvolvido como um guia teórico e prático introdutório sobre Redes Neurais Artificiais (RNAs), com o objetivo de apresentar os conceitos fundamentais e exemplos de implementação em Python de forma clara e acessível.

As Redes Neurais Artificiais são sistemas computacionais inspirados na estrutura e no funcionamento do cérebro humano. Elas utilizam unidades chamadas neurônios artificiais, organizadas em camadas e interconectadas por pesos sinápticos, os quais são ajustados automaticamente durante o aprendizado. Com isso, as RNAs são capazes de identificar padrões, realizar classificações e fazer previsões com base em dados, sendo amplamente utilizadas em diversas aplicações da inteligência artificial.

#1. Introdução ao modelo de Perceptron

##1.1. O que é o Perceptron?

###1.1.1 Definição e propósito

O Perceptron é considerado o primeiro modelo computacional de rede neural com capacidade de aprendizado supervisionado, sendo formulado por Frank Rosenblatt, em 1958. Seu objetivo era simular o processo de reconhecimento de padrões por organismos biológicos, estabelecendo uma ligação entre a estrutura neural e o comportamento adaptativo. Segundo Rosenblatt, o Perceptron é um "modelo probabilístico de organização e armazenamento de informação no cérebro", cuja função central é aprender a associar padrões de entrada a respostas esperadas com base em exemplos fornecidos previamente (ROSENBLATT, 1958).

Seu propósito pode ser simplificado nos seguintes pontos:
- Simular o processo de **aprendizado supervisionado** inspirado no cérebro humano.
- Estabelecer um **modelo matemático** capaz de reconhecer padrões a partir de exemplos.
- Demonstrar que é possível implementar **funções de decisão lineares** com neurônios artificiais simples.
- Investigar como a **informação é armazenada e organizada** em redes de conexões sinápticas.
- Propor um sistema que aprende ajustando **pesos sinápticos** com base no erro da resposta.
- Oferecer uma base teórica para a construção de redes neurais mais complexas no futuro.
- Explorar o potencial de redes com **unidades simples interconectadas** para gerar comportamento inteligente.

###1.1.2 Origem Histórica

A origem do modelo de Perceptron remonta à tentativa de compreender os mecanismos de aprendizagem e reconhecimento presentes nos sistemas nervosos biológicos. O trabalho seminal de McCulloch e Pitts (1943) já propunha uma estrutura lógica para descrever a atividade neural por meio de funções booleanas, estabelecendo os fundamentos do que viria a ser conhecido como redes neurais artificiais. Eles demonstraram que "a atividade de qualquer neurônio pode ser representada como uma proposição" e que redes neurais poderiam, em princípio, implementar qualquer função lógica computável com base em conexões sinápticas e limiares de ativação​.

Décadas depois, Frank Rosenblatt, em seu artigo de 1958, formalizou o modelo do Perceptron como uma máquina probabilística capaz de realizar tarefas de classificação por meio da aprendizagem dos pesos sinápticos. Segundo Rosenblatt, o Perceptron representa um "sistema nervoso hipotético" que armazena informação por meio de conexões modificáveis, sendo capaz de generalizar e reconhecer padrões com base em estímulos sensoriais​
. Esse modelo é considerado a primeira implementação prática de uma rede neural com capacidade de aprendizado supervisionado.

O entusiasmo inicial com o Perceptron, no entanto, foi confrontado com críticas importantes. O livro Perceptrons de Minsky e Papert (1969) demonstrou limitações fundamentais do modelo, especialmente sua incapacidade de resolver problemas não linearmente separáveis, como o XOR. Essa crítica desacelerou o avanço das redes neurais por quase duas décadas.

Somente nos anos 1980, com o trabalho de Rumelhart, Hinton e McClelland, foi possível revitalizar o campo por meio do conceito de Parallel Distributed Processing (PDP). Esses pesquisadores defenderam que o processamento inteligente poderia emergir da interação paralela de unidades simples de processamento, reforçando o papel das redes distribuídas e do aprendizado supervisionado por propagação do erro como alternativa viável e biologicamente plausível para modelar a cognição humana​
.

###1.1.3 Importância na evolução das redes neurais
O modelo do Perceptron teve um papel fundamental na história da Inteligência Artificial, sendo considerado o ponto de partida das redes neurais artificiais com capacidade de aprendizado. Proposto por Frank Rosenblatt em 1958, o Perceptron foi o primeiro sistema computacional que demonstrou ser possível ensinar uma máquina a reconhecer padrões por meio de ajustes iterativos em seus parâmetros internos, simulando o processo de aprendizagem observado em sistemas biológicos (ROSENBLATT, 1958).

Seu funcionamento baseado na atualização de pesos sinápticos a partir do erro da saída contribuiu para consolidar o paradigma conexionista como alternativa aos modelos simbólicos dominantes na época.

Ele foi essencial na evolução das redes neurais, pois:

- Foi o primeiro modelo de rede neural com capacidade de aprendizado supervisionado.
- Estabeleceu a ideia de ajuste de pesos sinápticos como mecanismo de aprendizagem.
- Inspirou o desenvolvimento de redes neurais multicamadas (MLPs) e o uso da retropropagação.
- Sua limitação com problemas como XOR motivou pesquisas sobre redes com maior capacidade expressiva.
- Fundamentou a transição de modelos simbólicos para modelos conexionistas na IA.
- Tornou-se referência obrigatória em estudos sobre o surgimento das redes neurais profundas.

##1.2. Inspiração Biológica
O Perceptron foi inspirado diretamente na estrutura e funcionamento dos neurônios biológicos, buscando representar, de maneira simplificada, o comportamento das células nervosas presentes no cérebro humano.

###1.2.1 Comparação entre neurônios biológicos e artificiais

No sistema nervoso biológico, os neurônios recebem sinais de entrada por meio de estruturas chamadas dendritos, que conduzem impulsos elétricos até o corpo celular (soma). Quando o potencial elétrico resultante ultrapassa um certo limiar, o neurônio dispara um impulso através do axônio, transmitindo a informação a outras células por meio de sinapses.

Já no modelo do Perceptron, essa dinâmica é representada de forma simplificada: os sinais de entrada (análogos aos impulsos recebidos pelos dendritos) são multiplicados por pesos sinápticos, somados, e então processados por uma função de ativação, que determina a saída do neurônio artificial, muitas vezes de forma binária. A função de ativação desempenha o papel do disparo ou não do potencial de ação no neurônio biológico.

Embora os neurônios artificiais não capturem toda a complexidade bioquímica e eletrofisiológica dos neurônios reais, sua estrutura matemática é suficiente para representar operações computacionais fundamentais, especialmente no contexto de aprendizado supervisionado e reconhecimento de padrões. Essa analogia simplificada permitiu o desenvolvimento de redes neurais artificiais como modelos computacionais inspirados no cérebro, mas adaptados às necessidades da computação digital.

###1.2.2 Elementos equivalentes: dendritos, corpo celular, axônio, sinapse
No processo de abstração que originou os neurônios artificiais, alguns dos principais componentes do neurônio biológico foram mapeados para elementos matemáticos com funções equivalentes no modelo computacional.

Os dendritos, que nos neurônios biológicos recebem sinais elétricos de outras células, correspondem às entradas do neurônio artificial. Cada uma dessas entradas é multiplicada por um valor chamado peso sináptico, que simula a força da conexão entre os neurônios.

O corpo celular (soma), responsável por integrar os sinais recebidos e decidir se o neurônio deve disparar, é representado por uma função de soma ponderada nos modelos artificiais.

Já o axônio, que transmite o impulso elétrico do corpo celular para outros neurônios, corresponde à saída do neurônio artificial.

Por fim, as sinapses, que regulam a passagem de sinais entre neurônios e podem ser fortalecidas ou enfraquecidas com o tempo, são modeladas pelos próprios pesos ajustáveis, que são modificados durante o processo de aprendizado para otimizar a resposta do modelo.
##1.3. Estrutura de um Perceptron
O Perceptron é um modelo simples, porém fundamental, de neurônio artificial. Ele realiza uma decisão binária com base em uma combinação linear das entradas, seguida por uma função de ativação. Abaixo estão seus componentes principais:

- Entradas 𝑥𝑖: Valores numéricos de entrada do modelo (por exemplo, características de um dado).

- Pesos 𝑤𝑖: Cada entrada está associada a um peso, que indica sua importância no cálculo da saída.

- Bias (viés) 𝑏: Um valor adicional que ajusta a saída independentemente das entradas, deslocando a função de ativação.

- Somatório 𝑢: O valor de ativação intermediário \( u \), antes de passar pela função de ativação, é calculado pela soma ponderada das entradas com seus respectivos pesos, mais o viés (bias):

$$
u = \sum_{i=1}^{n} w_i \cdot x_i + b
$$
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Onde, nessa formula, além das variáveis anterioresm existe o "n", que é o número total de entradas.

- Função de ativação (limiar):
A saída do Perceptron \( y \) é determinada pela função de ativação do tipo degrau (step function):

$$
f(u) =
\begin{cases}
1, & \text{se } u \geq 0 \\
0, & \text{se } u < 0
\end{cases}
$$

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Assim, a saída final é:

$$
y = f(u)
$$

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Essa função simula o comportamento "tudo ou nada" dos neurônios biológicos.

- Saída binária (0 ou 1): Como foi mencionado logo anteriormente, a saída de um Perceptron é binária, ou seja, assume apenas dois valores possíveis: 0 ou 1. Essa característica está diretamente relacionada à função de ativação utilizada, que normalmente é a função degrau (step function).

###1.3.1 Esquema visual do neurônio Perceptron
"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Criar a figura
fig, ax = plt.subplots(figsize=(13, 7))
ax.set_xlim(0, 15)
ax.set_ylim(2, 12)
ax.axis('off')  # remove os eixos

# === Entradas ponderadas ===
entradas = [r"$x_1 \cdot w_1$", r"$x_2 \cdot w_2$", r"$x_3 \cdot w_3$", r"$x_4 \cdot w_4$", r"$x_5 \cdot w_5$"]
y_coords = [10.5, 9, 7.5, 6, 4.5]

for i, y in enumerate(y_coords):
    ax.text(0.5, y, entradas[i], fontsize=14, ha='left')
    ax.plot([3, 6], [y, 6.5], 'k', lw=2)
    ax.plot(3, y, 'ko')  # ponto de origem

# === Colchete lateral "Inputs" ===
ax.plot([0.2, 0.2], [4.2, 10.8], 'k', lw=1.8)
ax.plot([0.2, 0.5], [10.8, 10.8], 'k', lw=1.8)
ax.plot([0.2, 0.5], [4.2, 4.2], 'k', lw=1.8)
ax.text(-0.2, 7.5, "Inputs", rotation=90, fontsize=12, va='center')

# === Bias ===
ax.arrow(4.0, 3, 2.0, 3.3, head_width=0.2, head_length=0.3, fc='dimgray', ec='dimgray', linestyle='--')
ax.text(3.4, 2.9, r"$+b$", fontsize=13, color='dimgray')

# === Círculo azul (neurônio somador) ===
neuron = patches.Circle((6, 6.5), 0.8, edgecolor='black', facecolor='#00B4D8', lw=2, zorder=10)
ax.add_patch(neuron)
ax.text(6, 6.5, r"$\sum$", ha='center', va='center', fontsize=18, zorder=11)

# === Bloco da função de ativação (EM CIMA DA LINHA) ===
activation = patches.FancyBboxPatch((7.5, 5.75), 3, 1.5, boxstyle="round,pad=0.2",
                                    edgecolor='black', facecolor='#b5f0b6', lw=2)
ax.add_patch(activation)
ax.text(9.0, 6.5,
        "f(u) = 1 se u ≥ 0\nf(u) = 0 se u < 0",
        ha='center', va='center', fontsize=11, family='monospace')

# === Linha do somador até ativação (por baixo da caixa)
ax.plot([6.8, 7.5], [6.5, 6.5], 'k', lw=2)

# === Linha da ativação até a saída
ax.plot([10.5, 12], [6.5, 6.5], 'k', lw=2)
ax.plot(12, 6.5, 'ko')
ax.text(12.2, 6.5, r"$y$", fontsize=14, va='center')
ax.text(12.2, 6.1, r"(0 or 1)", fontsize=11, va='top')

# === Fórmulas explicativas abaixo ===
ax.text(3.5, 1.3, r"$u = \sum_{i=1}^{n} x_i w_i + b$", fontsize=15)


# Título
plt.title("Perceptron: Função de Ativação sobre a Linha de Saída", fontsize=15, pad=20)

plt.show()

"""##1.4. Funcionamento Básico
Etapas do processo:

 ### Soma ponderada

Nesta primeira etapa, o Perceptron realiza o cálculo de uma soma ponderada entre as entradas 𝑥𝑖 e os respectivos pesos sinápticos 𝑤𝑖, adicionando ainda um termo de viés (bias) 𝑏. O objetivo é combinar todas as informações de entrada em um único valor numérico que será usado para tomar a decisão.

A formula utilizada é:
$
u = \sum_{i=1}^{n} x_i \cdot w_i + b
$
, onde:

𝑥
𝑖
: entrada
𝑖

𝑤
𝑖​
 : peso associado à entrada

𝑏: bias (viés), valor fixo que desloca a fronteira de decisão

𝑢: resultado da soma ponderada

Este valor 𝑢 representa a ativação líquida do neurônio, ou seja, o quanto o neurônio está estimulado a "disparar".

 ### Aplicação da função de ativação

Após o cálculo da ativação líquida
𝑢, o Perceptron aplica uma função de ativação, geralmente a função degrau (step function). Essa função é responsável por transformar
𝑢 em uma saída binária — ou seja, decidir se o neurônio será ativado (1) ou não (0).

A função de ativação usada no Perceptron clássico é definida como:

$
f(u) =
\begin{cases}
1, & \text{se } u \geq 0 \\
0, & \text{se } u < 0
\end{cases}
$

Essa função simula o comportamento de "tudo ou nada" dos neurônios biológicos: o neurônio só dispara (ativa) se a soma ponderada for suficiente (maior ou igual ao limiar, que normalmente é zero).

- Geração da saída

O resultado da função de ativação,
𝑦=𝑓(𝑢), é a saída final do Perceptron. Essa saída é um valor discreto e binário:

 𝑦=1: o Perceptron está ativado, ou seja, considera que a entrada pertence à classe positiva.

 𝑦=0: o Perceptron não está ativado, indicando a classe negativa.

##1.5. Fórmulas Matemáticas
 ###  Multiplicação Matricial/Vetorial

 O cálculo da saída do Perceptron pode ser representado como uma multiplicação vetorial, onde as entradas $ \mathbf{x} $ são multiplicadas pelos pesos $ \mathbf{w} $:

$
u = \mathbf{w}^\top \cdot \mathbf{x} + b
$

Ou seja, expandindo:

$
u = w_1 x_1 + w_2 x_2 + \dots + w_n x_n + b = \sum_{i=1}^{n} w_i x_i + b
$

Esse valor $ u $ é então passado pela função de ativação para produzir a saída $ y $.

---
 ###  Função de Custo

 No Perceptron clássico, a função de custo mais simples e utilizada no treinamento é o erro absoluto entre a saída desejada e a saída predita pelo modelo.

A fórmula é dada por:

$
E = y_{\text{desejado}} - y_{\text{predito}}
$

Onde:

- $ E > 0 $: O Perceptron subestimou a saída → precisa aumentar os pesos.
- $ E < 0 $: O Perceptron superestimou → precisa reduzir os pesos.
- $ E = 0 $: Classificação correta → nenhuma atualização é necessária.

Essa função de erro é usada diretamente na regra de atualização dos pesos, de forma simples e eficiente, ideal para problemas linearmente separáveis.

  ###  Regra de Atualização dos Pesos e Bias

 A regra de atualização dos pesos é o coração do aprendizado do Perceptron. Quando há erro, os pesos são atualizados da seguinte forma:


$ w_i \leftarrow w_i + \eta \cdot (y_{\text{real}} - y) \cdot x_i $

E o **bias** é atualizado da mesma forma:


$
b \leftarrow b + \eta \cdot (y_{\text{real}} - y)
$

Onde:
-
$ \eta
$: taxa de aprendizado (learning rate)
-
$ y_{\text{real}}
$: saída esperada
-
$ y
$: saída prevista pelo modelo
-
$ x_i
$: entrada associada ao peso
$ w_i
$

Esse processo se repete para cada amostra durante o treinamento, ajustando os pesos até que o Perceptron classifique corretamente (ou até atingir o número máximo de épocas).


##1.6. Algoritmo de Aprendizado do Perceptron
 ### Lógica do treinamento supervisionado

O Perceptron é treinado com exemplos rotulados — ou seja, cada entrada $ \mathbf{x} $ vem acompanhada da saída esperada $ y_{\text{real}} $. O modelo realiza uma previsão $ y_{\text{previsto}} $, e compara com a resposta correta. Se houver erro, os pesos são ajustados.

 ###  Atualização dos pesos:

Durante o treinamento supervisionado, o Perceptron aprende ajustando seus pesos com base nos erros que comete ao comparar a saída prevista com a saída real (esperada).

A regra de atualização tem como objetivo **corrigir os pesos sinápticos $ w_i $ e o bias $ b $ para que o modelo acerte nas próximas previsões.

 ### Papel da taxa de aprendizado 𝜂:

A taxa de aprendizado define a velocidade do ajuste:

- Pequena $ \eta \approx 0.01 $ → mudanças suaves, aprendizado estável porém lento
- Grande $ \eta \approx 1.0 $ → mudanças rápidas, porém pode causar oscilações e não convergir
> obs:
>- Se $ \eta $ for **muito alta**, os ajustes podem ser exagerados e causar instabilidade.
> - Se $ \eta $ for **muito baixa**, o modelo aprende devagar e pode não atingir a solução ideal em tempo hábil.
> - Valores comuns: $ \eta = 0.1 $, $ \eta = 0.01 $

O valor de $ \eta $ precisa ser bem escolhido para garantir que o Perceptron converja corretamente, ou seja, aprenda os padrões dos dados sem instabilidade.

##1.7. Convergência e Limitações
 ### Convergência garantida para problemas linearmente separáveis

O algoritmo do Perceptron possui uma propriedade importante: se os dados forem linearmente separáveis, ou seja, se existir uma linha (ou plano/hiperplano) que divida perfeitamente as classes, então o Perceptron irá convergir em um número finito de iterações.

Isso significa que ele irá encontrar os pesos corretos para classificar todas as amostras corretamente.

Matematicamente, isso foi provado pelo Teorema de Convergência do Perceptron, que afirma que:

> Se existe um vetor de pesos que separa as classes, o algoritmo do Perceptron o encontrará após um número finito de atualizações.

 ### Limitações do modelo simples (não resolve o XOR)

Apesar da sua utilidade, o Perceptron simples (de uma camada) tem limitações sérias. A principal é que ele **não consegue resolver problemas não linearmente separáveis**.

Um exemplo clássico é o problema lógico XOR (ou exclusivo), onde:

- As classes não podem ser separadas por uma linha reta
- Não existe combinação linear de entradas que permita ao Perceptron simples aprender a função

Ou seja:

> O Perceptron não consegue aprender padrões que exigem decisões não lineares.

 ### Introdução à motivação para redes multicamadas
 A limitação de resolver apenas problemas linearmente separáveis motivou a criação das redes neurais multicamadas, também chamadas de MLPs (Multi-Layer Perceptrons).

Essas redes incluem uma ou mais camadas ocultas, que aplicam transformações não lineares sobre os dados, permitindo que o modelo aprenda padrões mais complexos, como o caso do XOR.

As MLPs utilizam funções de ativação como:

- ReLU
- Sigmoide
- Tangente hiperbólica

Além disso, são treinadas com algoritmos como o backpropagation, que permite ajustar pesos em várias camadas de forma eficiente.


##1.8. Visualizações e Intuições Geométricas
###Fronteiras de decisão lineares:

O Perceptron é um classificador linear, ou seja, ele toma decisões com base em uma fronteira linear no espaço das entradas. Essa fronteira é determinada pela equação da soma ponderada:

$u = \sum_{i=1}^{n} w_i x_i + b$

Aplicando a função de ativação:

$y = f(u) =
\begin{cases}
1, & \text{se } u \geq 0 \\
0, & \text{se } u < 0
\end{cases}$

Essa equação define uma reta (em 2D), um plano (em 3D) ou um hiperplano (em dimensões superiores) que separa as classes.


###Separação de classes no plano cartesiano
Para problemas com duas entradas (ex: $x_1$ e $x_2$), o Perceptron pode ser visualizado **no plano cartesiano**. A fronteira de decisão será uma **reta** dada por:

$w_1 x_1 + w_2 x_2 + b = 0$

Isolando $x_2$:

$x_2 = -\frac{w_1}{w_2} x_1 - \frac{b}{w_2}$

Essa é a equação da **reta de separação**: divide o plano em duas regiões — uma onde a saída será 1 (classe positiva) e outra onde a saída será 0 (classe negativa).


##1.9. Variações e Extensões

###Perceptron com múltiplos neurônios (camada de saída com mais classes)
O Perceptron original foi projetado para resolver **problemas de classificação binária** (saída 0 ou 1). No entanto, ele pode ser estendido para resolver **problemas com mais de duas classes** utilizando uma **camada de saída com múltiplos neurônios**.

Cada **neurônio da camada de saída** é responsável por detectar uma **classe específica**. O modelo então retorna a classe cuja **saída do neurônio correspondente for a maior** (ou for 1, se usar codificação one-hot).

Dessa forma:
- 3 classes → 3 neurônios na saída
- Entrada $\mathbf{x}$ conectada a **cada neurônio com pesos distintos**
- Saída: vetor $[y_1, y_2, y_3]$, onde apenas uma posição será ativada

###Funções de ativação alternativas (ReLU, Sigmoid – apenas para contextualizar)

Embora o Perceptron clássico use a **função degrau**, redes neurais modernas utilizam funções de ativação contínuas e diferenciáveis, essenciais para o treinamento com **backpropagation**.

####  Sigmoid

A função sigmoid comprime o valor de entrada para o intervalo $(0, 1)$, sendo ideal para tarefas de probabilidade e classificação binária:

$
\sigma(x) = \frac{1}{1 + e^{-x}}
$

####  ReLU (Rectified Linear Unit)

Muito usada em redes profundas, a ReLU é simples e eficaz. Ela zera valores negativos e mantém os positivos:

$
\text{ReLU}(x) = \max(0, x)
$

---

###  Observação

>Essas funções não são usadas no Perceptron original, mas são fundamentais nas redes neurais modernas, como MLPs, CNNs e RNNs, pois permitem o uso de algoritmos baseados em derivadas.

#2. Aplicação do Perceptron aos problemas lógicos OR e AND

##2.1. Revisão dos Problemas Lógicos

O Perceptron pode ser aplicado a tarefas de classificação binária, como a reprodução do comportamento de operadores lógicos. Dois dos exemplos mais clássicos são as operações AND e OR, que envolvem entradas binárias e geram uma saída também binária.

###Tabelas verdade dos operadores lógicos AND e OR
Função AND:

| $x_1$ | $x_2$ | $ y$ = $x_1$ . $x_2$  |
|------:|------:|:------------------:|
|   0   |   0   |         0         |
|   0   |   1   |         0         |
|   1   |   0   |         0         |
|   1   |   1   |         1         |

A saída $y$ será 1 somente quando ambas as entradas forem 1.  
A função AND é linearmente separável, ou seja, o Perceptron consegue aprender essa relação com uma reta de separação adequada.

Função OR:

| $x_1$ | $x_2$ | $y$ = $x_1$ + $x_2$ |
|------:|------:|:------------------:|
|   0   |   0   |         0         |
|   0   |   1   |         1         |
|   1   |   0   |         1         |
|   1   |   1   |         1         |

A saída $y$ será 1 se pelo menos uma entrada for 1.  
O problema OR também é linearmente separável, o que significa que existe uma reta no plano cartesiano que divide corretamente as classes.

###Representação como problemas de classificação binária
Nos dois casos, estamos lidando com um conjunto de entradas binárias ($x_1$, $x_2$) e uma saída esperada binária ($y \in \{0,1\}$). Isso caracteriza um problema de classificação supervisionada com duas classes:

- Classe 0: saída negativa (falsa)  
- Classe 1: saída positiva (verdadeira)

Esses problemas são exemplos ideais para treinar e avaliar o funcionamento do Perceptron simples, pois são casos linearmente separáveis que permitem observar como os pesos são ajustados e como o modelo converge.

##2.2. Construção Manual dos Datasets
###Conjunto de dados com entrada binária (0 ou 1)
Nos problemas lógicos como AND e OR, as entradas são sempre valores binários, ou seja, $x_1$ e $x_2$ assumem apenas os valores 0 ou 1. Como são duas entradas possíveis, podemos gerar todas as combinações binárias de entrada com:

- $x_1 \in \{0, 1\}$
- $x_2 \in \{0, 1\}$

As combinações possíveis são:

- (0, 0)  
- (0, 1)  
- (1, 0)  
- (1, 1)
###Preparação dos pares (entrada, saída esperada)
O objetivo é treinar o Perceptron para aprender a mapear as entradas binárias para a saída correta, de acordo com o operador lógico que estamos simulando (AND ou OR).

Cada amostra do conjunto de dados é um par do tipo:

- Entrada: vetor $[x_1, x_2]$
- Saída esperada: $y_{\text{real}}$

- Para **AND**:

$
Y = \left[
\begin{array}{c}
0 \\
0 \\
0 \\
1 \\
\end{array}
\right]
$

- Para **OR**:

$
Y = \left[
\begin{array}{c}
0 \\
1 \\
1 \\
1 \\
\end{array}
\right]
$

---

### Cálculo da Soma Ponderada

O Perceptron irá calcular a saída através de uma soma ponderada das entradas com os pesos, somada a um bias $b$:

$$
u = \sum_{i=1}^{n} w_i \cdot x_i + b
$$

Para cada amostra, esse valor $u$ será passado para uma função de ativação do tipo degrau:

$$
f(u) =
\begin{cases}
1, & \text{se } u \geq 0 \\
0, & \text{se } u < 0
\end{cases}
$$

##2.3. Implementação do Perceptron
"""

import numpy as np
import matplotlib.pyplot as plt

# =============================
# Função de ativação (degrau)
# =============================
def degrau(u):
    return 1 if u >= 0 else 0

# =============================
# Inicialização do dataset lógico OR
# =============================
entradas = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Saídas esperadas para OR
saidas = np.array([0, 1, 1, 1])

# =============================
# Parâmetros iniciais
# =============================
epocas = 20              # número máximo de épocas
eta = 0.01                # taxa de aprendizado
n_amostras, n_entradas = entradas.shape

# Inicialização dos pesos (zeros ou aleatórios)
pesos = np.random.uniform(-1, 1, size=n_entradas)
bias = 0.0

# Histórico para visualização
historico_pesos = []
historico_erro = []

# =============================
# Treinamento
# =============================
for epoca in range(epocas):
    erro_total = 0
    for i in range(n_amostras):
        x = entradas[i]
        y_real = saidas[i]

        # 1. Calcular a soma ponderada
        u = np.sum(pesos * x) + bias

        # 2. Aplicar função de ativação
        y_pred = degrau(u)

        # 3. Calcular erro
        erro = y_real - y_pred
        erro_total += abs(erro)

        # 4. Atualizar pesos e bias
        for j in range(n_entradas):
            pesos[j] += eta * erro * x[j]
        bias += eta * erro

    # Armazena histórico
    historico_pesos.append(pesos.copy())
    historico_erro.append(erro_total)

    # Print da época
    print(f"Época {epoca+1}: Erro Total = {erro_total}")

    # Critério de parada: erro zero
    if erro_total == 0:
        print("Convergência atingida.")
        break

"""## 2.4. Gráfico de Convergência"""

import matplotlib.pyplot as plt
import numpy as np

# Converter o histórico de pesos para array
pesos_array = np.array(historico_pesos)

# Criar a figura com dois subgráficos
plt.figure(figsize=(12, 5))

#  Erro total por época
plt.subplot(1, 2, 1)
plt.plot(historico_erro, marker='o', color='red')
plt.title("Erro Total por Época")
plt.xlabel("Época")
plt.ylabel("Erro Total")
plt.grid(True)

#  Evolução dos pesos
plt.subplot(1, 2, 2)
for i in range(pesos_array.shape[1]):
    plt.plot(pesos_array[:, i], marker='o', label=f"$w_{i+1}$")
plt.title("Evolução dos Pesos")
plt.xlabel("Época")
plt.ylabel("Valor dos Pesos")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

"""##2.5. Avaliação do Modelo


"""

print("\n=== Avaliação do Modelo Treinado ===\n")

for i in range(len(entradas)):
    x = entradas[i]
    y_real = saidas[i]

    # Soma ponderada com os pesos finais
    u = np.sum(x * pesos) + bias

    # Previsão com a função de ativação
    y_pred = degrau(u)

    # Impressão do resultado
    print(f"Entrada: {x} → Saída esperada: {y_real} | Saída prevista: {y_pred}")

"""##2.6. Visualização dos Resultados
###Gráficos de dispersão dos dados
Cada ponto no gráfico representa uma amostra binária com coordenadas ($x_1$, $x_2$). Os pontos foram coloridos conforme sua classe esperada:

- Vermelho: saída esperada 0 (classe negativa)
- Azul: saída esperada 1 (classe positiva)


###Exibição da fronteira de decisão
A reta preta pontilhada representa a **fronteira de decisão aprendida pelo Perceptron**, calculada a partir da equação:

$w_1 x_1 + w_2 x_2 + b = 0$

Essa fronteira divide o plano em duas regiões:

- Acima da reta: pontos onde $y = 1$
- Abaixo da reta: pontos onde $y = 0$

###Análise visual: separabilidade linear

Se os pontos das duas classes estiverem em lados opostos da reta, o problema é linearmente separável — como nos casos de OR e AND.  
Se isso não for possível (como no caso do XOR), o Perceptron simples não consegue encontrar uma reta que separe perfeitamente as classes, evidenciando sua limitação.

"""

import matplotlib.pyplot as plt

# Preparar dados por classe para plotar com cores diferentes
classe_0 = entradas[saidas == 0]
classe_1 = entradas[saidas == 1]

# Criar a figura
plt.figure(figsize=(7, 6))

# Plotar os pontos de cada classe
plt.scatter(classe_0[:, 0], classe_0[:, 1], color='red', label='Classe 0 (Saída = 0)')
plt.scatter(classe_1[:, 0], classe_1[:, 1], color='blue', label='Classe 1 (Saída = 1)')

# Título e rótulos
plt.title("Dispersão dos Dados e Fronteira de Decisão do Perceptron")
plt.xlabel("$x_1$")
plt.ylabel("$x_2$")
plt.xlim(-0.1, 1.1)
plt.ylim(-0.1, 1.1)

# Plotar a fronteira de decisão (reta: w1*x1 + w2*x2 + b = 0)
# Isolar x2: x2 = -(w1/w2)*x1 - b/w2
if pesos[1] != 0:
    x1_vals = np.linspace(-0.1, 1.1, 100)
    x2_vals = -(pesos[0] * x1_vals + bias) / pesos[1]
    plt.plot(x1_vals, x2_vals, color='black', linestyle='--', label='Fronteira de Decisão')
else:
    # Caso especial: reta vertical
    x_val = -bias / pesos[0]
    plt.axvline(x=x_val, color='black', linestyle='--', label='Fronteira de Decisão')

plt.legend()
plt.grid(True)
plt.show()

"""##2.7. Análise da Fronteira de Decisão
###Interpretação geométrica dos pesos como coeficientes da reta
Após o treinamento, os pesos $w_1$, $w_2$ e o bias $b$ do Perceptron podem ser interpretados geometricamente como os coeficientes da equação de uma reta no plano cartesiano:

$w_1 x_1 + w_2 x_2 + b = 0$

Reescrevendo para isolar $x_2$:

$x_2 = -\dfrac{w_1}{w_2} x_1 - \dfrac{b}{w_2}$

Essa é a equação de uma reta com:

- Inclinação (coeficiente angular): $-\dfrac{w_1}{w_2}$
- Intercepto com o eixo $x_2$: $-\dfrac{b}{w_2}$

###Como a reta se ajusta para classificar corretamente os dados
Durante o treinamento, a reta de decisão é ajustada alterando os pesos. A cada erro cometido, o algoritmo atualiza os valores de $w_1$, $w_2$ e $b$, movendo e rotacionando a reta até que ela divida corretamente os pontos das duas classes.

A reta define regiões da seguinte forma:

- Se $w_1 x_1 + w_2 x_2 + b \geq 0$, a saída $y = 1$
- Se $w_1 x_1 + w_2 x_2 + b < 0$, a saída $y = 0$

###Demonstração com matplotlib (sem bibliotecas de IA)

Abaixo, mostramos graficamente a reta aprendida e como ela separa os dados no plano bidimensional.

"""

import matplotlib.pyplot as plt

# Preparar dados por classe para plotar com cores diferentes
classe_0 = entradas[saidas == 0]
classe_1 = entradas[saidas == 1]

# Recriar a animação no mesmo estilo do código de dispersão e reta final

fig, ax = plt.subplots(figsize=(7, 6))
ax.set_xlim(-0.1, 1.1)
ax.set_ylim(-0.1, 1.1)
ax.set_xlabel("$x_1$")
ax.set_ylabel("$x_2$")
ax.set_title("Dispersão dos Dados e Evolução da Fronteira de Decisão (OR)")
ax.grid(True)

# Dados das classes
classe_0 = entradas[saidas == 0]
classe_1 = entradas[saidas == 1]
ax.scatter(classe_0[:, 0], classe_0[:, 1], color='red', label='Classe 0 (Saída = 0)')
ax.scatter(classe_1[:, 0], classe_1[:, 1], color='blue', label='Classe 1 (Saída = 1)')

# Elementos dinâmicos da animação
linha, = ax.plot([], [], 'k--', label='Fronteira de Decisão')
epoca_txt = ax.text(0.02, 1.08, '', transform=ax.transAxes)
ax.legend()

# Função de atualização por época
def update_anim(epoch):
    w = historico_pesos[epoch]
    b = bias  # usando o bias final (não foi salvo por época)
    epoca_txt.set_text(f"Época: {epoch + 1}")
    if w[1] != 0:
        x_vals = np.linspace(-0.1, 1.1, 100)
        y_vals = -(w[0] * x_vals + b) / w[1]
        linha.set_data(x_vals, y_vals)
    else:
        x_val = -b / w[0]
        linha.set_data([x_val, x_val], [-0.1, 1.1])
    return linha, epoca_txt

# Criar e exibir animação
anim_final = FuncAnimation(fig, update_anim, frames=len(historico_pesos), interval=800, blit=True)
plt.close()
HTML(anim_final.to_jshtml())

"""###Simulação do AND"""

# Redefinir tudo para o problema lógico AND

# Dataset AND
entradas_and = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
saidas_and = np.array([0, 0, 0, 1])

# Reconfigurar parâmetros
epocas = 20
eta = 0.1
n_amostras, n_entradas = entradas_and.shape
pesos = np.random.uniform(-1, 1, size=n_entradas)  # pesos aleatórios
bias = np.random.uniform(-1, 1)  # bias aleatório

# Histórico
historico_pesos = []
historico_erro = []

# Função de ativação
def degrau(u):
    return 1 if u >= 0 else 0

# Treinamento
for epoca in range(epocas):
    erro_total = 0
    for i in range(n_amostras):
        x = entradas_and[i]
        y_real = saidas_and[i]
        u = np.sum(x * pesos) + bias
        y_pred = degrau(u)
        erro = y_real - y_pred
        erro_total += abs(erro)
        for j in range(n_entradas):
            pesos[j] += eta * erro * x[j]
        bias += eta * erro
    historico_pesos.append(pesos.copy())
    historico_erro.append(erro_total)
    if erro_total == 0:
        break

# Animação da reta (AND)
fig, ax = plt.subplots(figsize=(7, 6))
ax.set_xlim(-0.1, 1.1)
ax.set_ylim(-0.1, 1.1)
ax.set_xlabel("$x_1$")
ax.set_ylabel("$x_2$")
ax.set_title("Dispersão dos Dados e Evolução da Fronteira de Decisão (AND)")
ax.grid(True)

# Separar as classes
classe_0 = entradas_and[saidas_and == 0]
classe_1 = entradas_and[saidas_and == 1]
ax.scatter(classe_0[:, 0], classe_0[:, 1], color='red', label='Classe 0 (Saída = 0)')
ax.scatter(classe_1[:, 0], classe_1[:, 1], color='blue', label='Classe 1 (Saída = 1)')

linha, = ax.plot([], [], 'k--', label='Fronteira de Decisão')
epoca_txt = ax.text(0.02, 1.08, '', transform=ax.transAxes)
ax.legend()

def update_and(epoch):
    w = historico_pesos[epoch]
    b = bias  # bias final
    epoca_txt.set_text(f"Época: {epoch + 1}")
    if w[1] != 0:
        x_vals = np.linspace(-0.1, 1.4, 100)
        y_vals = -(w[0] * x_vals + b) / w[1]
        linha.set_data(x_vals, y_vals)
    else:
        x_val = -b / w[0]
        linha.set_data([x_val, x_val], [-0.1, 1.1])
    return linha, epoca_txt

anim_and = FuncAnimation(fig, update_and, frames=len(historico_pesos), interval=800, blit=True)
plt.close()
HTML(anim_and.to_jshtml())

"""##2.8. Discussão dos Resultados
###Por que o Perceptron funciona para OR e AND?
O Perceptron resolve corretamente os problemas lógicos OR e AND porque ambos são **linearmente separáveis**. Isso significa que é possível traçar uma **reta (fronteira de decisão)** que divide perfeitamente os pontos das duas classes no plano cartesiano.

- No caso do OR, a saída é 1 se pelo menos uma das entradas for 1.
- No caso do AND, a saída é 1 somente quando **ambas** as entradas forem 1.

Em ambos os casos, o modelo consegue **ajustar os pesos e bias** de forma que a função de ativação classifique corretamente todas as amostras.


###Influência da taxa de aprendizado e número de épocas
A taxa de aprendizado ($\eta$) define o tamanho do passo na atualização dos pesos a cada erro cometido. Valores diferentes afetam o comportamento do treinamento:

- $\eta$ muito pequeno: aprendizagem lenta (leva muitas épocas para convergir)
- $\eta$ muito alto: pode causar oscilação e dificultar a convergência

O número máximo de épocas define até quando o modelo tenta aprender. Se for muito baixo, o modelo pode não ter tempo suficiente para ajustar corretamente os pesos. Por isso, é importante equilibrar $\eta$ e o número de épocas.

---

###Limitações do modelo simples mesmo em problemas lineares (por ex., quando dados ruidosos são inseridos)
Mesmo sendo eficiente para problemas simples e lineares, o Perceptron **tem limitações** importantes:

- **Não consegue aprender padrões não-lineares**, como o problema **XOR**
- É sensível a **ruído nos dados**: se os pontos não forem perfeitamente separáveis, o modelo pode nunca convergir
- Usa uma **função de ativação não diferenciável (degrau)**, o que impede a utilização de métodos de otimização mais sofisticados como o gradiente descendente

Essas limitações levaram ao desenvolvimento de modelos mais avançados, como as **Redes Neurais Multicamadas (MLPs)**, capazes de resolver problemas mais complexos.

#3. Discussão do problema XOR e suas implicações para a evolução das Redes Neurais

##3.1. Revisão do Problema Lógico XOR
###Tabela verdade do operador XOR

| $x_1$ | $x_2$ | $y$ = $x_1$ ⊕ $x_2$ |
|:-----:|:-----:|:---------------------:|
|  0    |  0    |          0           |
|  0    |  1    |          1           |
|  1    |  0    |          1           |
|  1    |  1    |          0           |

###Interpretação lógica:
O operador XOR (ou "OU exclusivo") retorna 1 somente quando as entradas são diferentes.  
Ou seja:

- Se $x_1 \neq x_2$ então $y = 1$
- Se $x_1 = x_2$ então $y = 0$

###Representação gráfica: pontos no plano cartesiano
No plano cartesiano, os pontos positivos e negativos **não podem ser separados por uma única reta**. Isso significa que o problema **XOR não é linearmente separável** — é justamente o exemplo clássico que expõe as limitações do Perceptron simples.

Abaixo, vamos construir o dataset manualmente e visualizar essa impossibilidade geometricamente.

O conjunto de dados para o problema XOR contém todas as combinações binárias de duas entradas, com suas respectivas saídas conforme a operação lógica XOR:

- Entrada: $[0, 0]$ → Saída esperada: $0$
- Entrada: $[0, 1]$ → Saída esperada: $1$
- Entrada: $[1, 0]$ → Saída esperada: $1$
- Entrada: $[1, 1]$ → Saída esperada: $0$

Vamos representar graficamente os pontos:

- Pontos com saída $y = 1$ serão destacados em azul
- Pontos com saída $y = 0$ em vermelho

Essa visualização mostrará que **não há como separar as duas classes com uma única linha reta**, destacando a **inadequação do Perceptron simples** para esse tipo de problema.
"""

import matplotlib.pyplot as plt
import numpy as np

# Dataset XOR: entradas e saídas esperadas
entradas_xor = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
saidas_xor = np.array([0, 1, 1, 0])

# Separar classes para visualização
classe_0 = entradas_xor[saidas_xor == 0]
classe_1 = entradas_xor[saidas_xor == 1]

# Criar gráfico novamente com seta indicativa de tentativa de separação
plt.figure(figsize=(6, 6))
plt.scatter(classe_0[:, 0], classe_0[:, 1], color='red', label='Classe 0 (Saída = 0)')
plt.scatter(classe_1[:, 0], classe_1[:, 1], color='blue', label='Classe 1 (Saída = 1)')

# Tentativa de separação com seta (visualização incorreta intencional)
plt.arrow(0.2, 1.2, 0.6, -1.2, head_width=0.00, head_length=0.1, fc='gray', ec='gray', linestyle='--')
plt.text(0.5, 1.25, "Tentativa de separação", fontsize=10, color='gray')

plt.title("Visualização do Problema XOR com Tentativa de Separação Linear")
plt.xlabel("$x_1$")
plt.ylabel("$x_2$")
plt.xlim(-0.1, 1.1)
plt.ylim(-0.1, 1.3)
plt.grid(True)
plt.legend()
plt.show()

"""##3.3. Testando o Perceptron no XOR
###Utilização da mesma implementação do Perceptron simples
Nesta etapa, aplicamos a **mesma implementação do Perceptron** usada nos problemas OR e AND, sem qualquer modificação, para verificar seu desempenho no problema lógico XOR.

###Treinamento com os dados do XOR
Utilizamos o conjunto:

- Entradas: combinações binárias de duas variáveis
- Saídas esperadas: 0 quando as entradas são iguais, 1 quando são diferentes

Apesar de o treinamento ocorrer normalmente (com atualização de pesos e bias a cada erro), o modelo **não consegue convergir**, pois os dados **não são linearmente separáveis**.

###Resultados obtidos: falhas na classificação correta

Isso evidencia a **limitação do modelo simples** diante de problemas não-lineares, como é o caso do XOR.

> A solução para esse tipo de problema só é possível com modelos mais robustos, como **redes neurais multicamadas (MLP)** com funções de ativação não-lineares.

Pode ser visto os resultados abaixo:
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# Dataset XOR
entradas_xor = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
saidas_xor = np.array([0, 1, 1, 0])

# Parâmetros
epocas = 20
eta = 0.1
n_amostras, n_entradas = entradas_xor.shape
#np.random.seed(-1) #para reprotutibilidade
pesos = np.random.uniform(-1, 1, size=n_entradas)
bias = np.random.uniform(-1, 1)

# Histórico
historico_pesos_xor = []
historico_erro_xor = []

def degrau(u):
    return 1 if u >= 0 else 0

# Treinamento
for epoca in range(epocas):
    erro_total = 0
    for i in range(n_amostras):
        x = entradas_xor[i]
        y_real = saidas_xor[i]
        u = np.sum(x * pesos) + bias
        y_pred = degrau(u)
        erro = y_real - y_pred
        erro_total += abs(erro)
        for j in range(n_entradas):
            pesos[j] += eta * erro * x[j]
        bias += eta * erro
    historico_pesos_xor.append(pesos.copy())
    historico_erro_xor.append(erro_total)

# === Mostrar a reta final que o Perceptron tentou usar ===
classe_0 = entradas_xor[saidas_xor == 0]
classe_1 = entradas_xor[saidas_xor == 1]

fig_final, ax_final = plt.subplots(figsize=(6, 6))
ax_final.set_xlim(-0.1, 1.1)
ax_final.set_ylim(-0.1, 1.1)
ax_final.set_xlabel("$x_1$")
ax_final.set_ylabel("$x_2$")
ax_final.set_title("Reta Final do Perceptron (XOR)")
ax_final.grid(True)
ax_final.scatter(classe_0[:, 0], classe_0[:, 1], color='red', label='Classe 0')
ax_final.scatter(classe_1[:, 0], classe_1[:, 1], color='blue', label='Classe 1')

if pesos[1] != 0:
    x_vals = np.linspace(-0.1, 1.1, 100)
    y_vals = -(pesos[0] * x_vals + bias) / pesos[1]
    ax_final.plot(x_vals, y_vals, 'k--', label='Fronteira Final')
else:
    x_val = -bias / pesos[0]
    ax_final.axvline(x=x_val, color='black', linestyle='--', label='Fronteira Final')
ax_final.legend()
plt.show()

# === Visualizar o gráfico de erro por época ===
plt.figure(figsize=(6, 4))
plt.plot(historico_erro_xor, marker='o', color='darkred')
plt.title("Erro Total por Época - Treinamento com XOR")
plt.xlabel("Época")
plt.ylabel("Erro Total")
plt.grid(True)
plt.show()

# === Gerar uma animação com a evolução da reta no XOR ===
fig_anim, ax_anim = plt.subplots(figsize=(6, 6))
ax_anim.set_xlim(-0.1, 1.1)
ax_anim.set_ylim(-0.1, 1.1)
ax_anim.set_xlabel("$x_1$")
ax_anim.set_ylabel("$x_2$")
ax_anim.set_title("Evolução da Fronteira de Decisão (XOR)")
ax_anim.grid(True)
ax_anim.scatter(classe_0[:, 0], classe_0[:, 1], color='red', label='Classe 0')
ax_anim.scatter(classe_1[:, 0], classe_1[:, 1], color='blue', label='Classe 1')
linha, = ax_anim.plot([], [], 'k--')
epoca_txt = ax_anim.text(0.02, 1.08, '', transform=ax_anim.transAxes)
ax_anim.legend()

def update(epoch):
    w = historico_pesos_xor[epoch]
    b = bias  # utilizando o bias final
    epoca_txt.set_text(f"Época: {epoch + 1}")
    if w[1] != 0:
        x_vals = np.linspace(-0.1, 1.1, 100)
        y_vals = -(w[0] * x_vals + b) / w[1]
        linha.set_data(x_vals, y_vals)
    else:
        x_val = -b / w[0]
        linha.set_data([x_val, x_val], [-0.1, 1.1])
    return linha, epoca_txt

anim = FuncAnimation(fig_anim, update, frames=len(historico_pesos_xor), interval=800, blit=True)
plt.close()
HTML(anim.to_jshtml())

"""3.4. Visualização da Falha do Perceptron
Gráfico mostrando que os dados não são linearmente separáveis

Tentativas frustradas de ajustar uma reta que separe os dados

Ilustração clara da limitação do modelo linear

3.5. Entendendo a Limitação Teórica
Conceito de linear separability

Prova informal de que XOR não pode ser separado com uma única reta

Implicação direta: Perceptron simples não é suficiente

3.6. Implicações Históricas e Científicas
Impacto da crítica de Minsky & Papert (1969) sobre o Perceptron

Queda do interesse em redes neurais na década de 1970 (inverno da IA)

Redescoberta e evolução nos anos 1980 com o surgimento do Backpropagation

3.7. Solução: Redes Neurais Multicamadas (MLP)
Introdução ao conceito de camada oculta

Como uma MLP pode resolver o XOR

Antecipação do próximo passo na evolução das RNAs

3.8. Conclusão e Conexão com o Futuro
O problema XOR como marco histórico e ponto de virada

Importância da limitação para o avanço científico

Encaminhamento para estudos sobre redes multicamadas e deep learning
"""



"""#Referências
MCCULLOCH, Warren S.; PITTS, Walter. A logical calculus of the ideas immanent in nervous activity. The Bulletin of Mathematical Biophysics, v. 5, p. 115–133, 1943. Reimpresso em: Bulletin of Mathematical Biology, v. 52, n. 1/2, p. 99–115, 1990.

ROSENBLATT, Frank. The perceptron: a probabilistic model for information storage and organization in the brain. Psychological Review, v. 65, n. 6, p. 386–408, 1958.

RUMELHART, David E.; HINTON, Geoffrey E.; MCCLELLAND, James L. Learning internal representations by error propagation. In: RUMELHART, D. E.; MCCLELLAND, J. L.; PDP Research Group (Ed.). Parallel Distributed Processing: Explorations in the Microstructure of Cognition. v. 1: Foundations. Cambridge, MA: MIT Press, 1986. p. 318–362.

Du, K.-L.; Leung, C.-S.; Mow, W.H.; Swamy, M.N.S. Perceptron: Learning, Generalization, Model Selection, Fault Tolerance, and Role in the Deep Learning Era. Mathematics 2022, 10, 4730. https://doi.org/10.3390/math10244730
"""